---

- hosts: webservers
  gather_facts: false
  
  tasks:
    - name: Create a root directory
      ansible.builtin.file:
        state: directory
        path: "{{ caddy_file_dir }}"
      become: true

    - name: Install required packages for caddy
      ansible.builtin.apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
        update_cache: true
      become: true

    - name: Prepare for caddy installation
      ansible.builtin.shell: |
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
      become: true
  
    - name: Install caddy
      ansible.builtin.apt:
        name: caddy
        update_cache: true
      become: true
